---
title: "test_citibike_prediction.Rmd"
output: html_document
date: '2022-06-17'
---
## Setup
```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(scales)
library(modelr)
library(lubridate)
library(broom)
theme_set(theme_bw())
options(repr.plot.width=4, repr.plot.height=3)
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data
```{r message=FALSE, warning=FALSE}
load('.RData')
load('trips_2015.RData')
```

# Modify 2015 data to feed into the model

```{r}
#trips <- trips %>% select(ymd) %>% group_by(ymd) %>% summarise(num_trips = n())
#trips_per_day_2015 <- left_join(trips, weather, by="ymd")
trips_per_day_2015 <- trips_per_day_2015%>%
  mutate(day = wday(ymd))%>%
  mutate(weekday = ifelse(day==6|day==7, 0, 1)) %>%
  mutate(rainy = (prcp >= 0.5))
holidays <- read_csv("holidays.csv", col_names = c('sr','ymd','name')) %>% select(ymd) %>% mutate(holiday=1)
trips_per_day_2015 <- left_join(trips_per_day_2015, holidays, by="ymd") %>% mutate(holiday = ifelse(is.na(holiday), 0, 1))

```

## Model description
```{r}
summary(final_model)
```

## Test on 2015 data
```{r message=FALSE, warning=FALSE}
rmse(final_model,trips_per_day_2015)
rsquare(final_model,trips_per_day_2015)
trips_per_day_2015 <- trips_per_day_2015 %>%
  add_predictions(final_model) %>%
  mutate(split = "2015")
```

